#!/bin/bash

BRANCH=`pwd`
TRUNK=../../trunk
. `dirname $0`/svnmerge-setup.sh
# sets up PWD_IS_TRUNK and TRUNK_IS_MODIFIED

if test -n "$PWD_IS_TRUNK"
then
    echo Please execute this in BRANCH directory
    exit 1
fi
        
if test -n "$1"
then
    TRUNK=$1
fi

svnmerge avail -bd -S $TRUNK
